#!/usr/bin/env bash
typos -V

TMPDIR=/tmp/update__typos
mkdir -p "${TMPDIR}"

cd "${TMPDIR}" || exti 1
wget -q https://api.github.com/repos/crate-ci/typos/releases/latest -O - \
    | grep 'browser_download_url' | grep linux | grep -o 'http[^"]*' \
    | xargs -I {} wget -q {} -O "${TMPDIR}/typos.tar.gz"

tar xf "${TMPDIR}/typos.tar.gz"
mv ./typos ~/local/bin

rm -rf "${TMPDIR}"
typos -V
