[tools]
"aqua:go-task/task" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jdx/usage" = "latest"
actionlint = "latest"
delta = "latest"
gh = "latest"
go = "latest"
neovim = "latest"
node = "lts"
peco = "latest"
pnpm = "latest"
python = "3.13.12"
shfmt = "latest"
typos = "latest"
uv = "latest"

[settings]
lockfile = true
