[tools]
actionlint = "latest"
delta = "latest"
gh = "latest"
go = "latest"
hadolint = "latest"
herdr = "latest"
neovim = "latest"
node = "lts"
peco = "latest"
pinact = "latest"
pnpm = "latest"
python = "3.14.5"
shfmt = "latest"
task = "latest"
typos = "latest"
usage = "latest"
uv = "latest"
zizmor = "latest"

[settings]
install_before = "7d"
lockfile = true
