[tools]
actionlint = "latest"
go = "latest"
hadolint = "latest"
neovim = "latest"
node = "lts"
peco = "latest"
pnpm = "latest"
python = "3.13.5"
shfmt = "latest"
task = "latest"
typos = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
